title: Learn Without Limits CIC Blog
description: Blog articles from Learn Without Limits CIC on ALN, education, online safety and system reform.

url: "https://blog.learnwithoutlimitscic.org"
baseurl: ""

lang: en-GB
timezone: Europe/London
author: Learn Without Limits CIC

markdown: kramdown
permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "en"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
